{{ if eq .Values.lotteConfig.configMap.external false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.lotteConfig.data | nindent 2 }}
{{- end }}