{{ if eq .Values.lotteSecrets.secret.external false }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.lotteSecrets.data | nindent 2 }}
{{- end }}
